### ISSUE TITLE
How do i add this to the game?

### ISSUE THREAD

**Issue by 330CanWalk** [5and5/BO1-Strat_Tester#14]
I have been struggling to find a way on how to implement this to my game

**Comment by TTS4life** [comment]
I made a guide a few months ago that might be able to solve your problems. You can find it here: https://youtu.be/rTJs7evNRXo

Note that the mod *should* be able to work with Plutonium if you prefer it over game_mod, but this mod was made around game_mod's implementation of mod support, so YMMV if you go with Plutonium. Having game_mod installed has no effect on your Plutonium installation and vice/versa.

**Comment by 330CanWalk** [comment]
![image](https://user-images.githubusercontent.com/111645771/185751794-7a3d8b24-a0e2-4e06-be77-31f6684cce4d.png)
Im on pluto and when i open the .bat it  doesnt work.

**Comment by TTS4life** [comment]
If the game is not booting at all it is more likely a Plutonium issue than a Strat Tester issue. Some things you could do:

- Use a legitimate copy of BO1 (or the supported torrent by the Plutonium team if you know what you're doing)
- Verify integrity of game cache on Steam (if you are using a legitimate copy)
- Review the process of setting up Plutonium for BO1
- Opt to use game_mod instead

BO1 Plutonium is still in its infancy so there's bound to be issues. Once you can get the game to boot and you see the "Mods" option on the TV you're in good shape.

Hope this helps

**Comment by 330CanWalk** [comment]
I did fix the strat tester for plutonium by just not using the Game_Mod v1.3.2 which was gaving me problems. Since pluto has its own mod usage i simply loaded the tester without gamemod and it actually worked. 
The tester is awesome.
Tysm for your help .

**Comment by TTS4life** [comment]
Enjoy practicing 😄
