### ISSUE TITLE
Weak zombies in Call of the Dead High rounds

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-Strat_Tester#15]
Hello,

On Call of the Dead, in high rounds, zombies are supposed to die when they're going in the water with 5% or less of their base health. But at the beginning of the game, they die with 50% or less of their base health. This percentage decreases by 5 each round until it reaches 5%. So above round 10, it would be nice if that value was equal to 5% instead of 50%.

Thanks

**Comment by TTS4life** [comment]
Percentage was being calculated between rounds, and by how many rounds had passed, not what round you were on. Modified to calculate at the beginning of the round and factor in what round you're on for calculation. Implemented for next release.
