### ISSUE TITLE
Bring back round 80

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-Strat_Tester#17]
Hello,

I noticed round 80 was removed completly from the round settings. I would recommand adding it back ONLY for Call of the Dead. The reason behind that is to test how effective are weapons like Scavenger, Ray Gun and M72 Law. I would even recommand using another list of rounds for Call of the Dead solo (like 80, 82, 84, 86, 88, 90). I don't know what would be possible to make it user friendly actually. But in my opinion, it would be very useful for people who want to try and optimize Call of the Dead solo.

Thanks

**Comment by TTS4life** [comment]
I don't think it's clearly posted anywhere, but you can start on a round of your choice by typing `/round_number <round>` and restarting level. Hope this helps.

**Comment by llPh3NiXll** [comment]
Didn't know that, thanks !

**Comment by llPh3NiXll** [comment]
Didn't know that, thanks !
