### ISSUE TITLE
https://github.com/Loyalists/gflbo1/releases/tag/release

### ISSUE THREAD

**Issue by uewo** [5and5/BO1-Strat_Tester#23]

**Comment by TTS4life** [comment]
If the request here is "add support for this mod into strat tester", the answer is no. The purpose of this mod is to help people practice and create strategies for high round games or speedruns, which requires the game to be as authentic as possible. The focus is not on cosmetic mods such as this. If you have feature requests or bugs related to strat tester, feel free to open a new issue, but requests for cosmetic mods like this will be instantly closed.
