### ISSUE TITLE
Five windows setting bug

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-Strat_Tester#32]
When setting the disabled windows on Five, depending on the different combinations, it doesn't give the same result with the same windows. 
Here is the list : 
![image](https://github.com/5and5/BO1-StratTester/assets/32444889/c121cee2-6427-42d7-9a42-6ec44258d929)
(Tested by Slewya)

Thanks.

**Comment by TTS4life** [comment]
Part of me feels like there might be a bug in reimagined as well since most the windows code is borrowed from there...Thanks for the chart, makes it really easy to decipher which ones are wrong
